from customtkinter import *
from spinbox import *
from events import *

def init_gui(app):
    # Hier kannst du globale GUI-Einstellungen vornehmen
    # z. B. die Standard-Farbthemen und den Erscheinungsmodus setzen (bereits in kuppelstopper.py gemacht)
    pass

def create_tabs(app):
    app.root.TabView = CTkTabview(app.root, anchor='nw', corner_radius=0, fg_color='transparent')
    app.root.TabView.pack(expand=1, side='top', fill='both', padx=5, pady=5)
    app.root.FTab1 = app.root.TabView.add(app.NAME_TAB1)
    app.root.FTab2 = app.root.TabView.add(app.NAME_TAB2)
    app.root.FTab3 = app.root.TabView.add(app.NAME_TAB3)

def create_tab1(app):
    app.root.Entry = CTkEntry(app.root.FTab1, corner_radius=0, placeholder_text='Gruppenname')
    app.root.Entry.pack(side='top', fill='x', padx=10, pady=10)
    app.root.Entry.bind('<Return>', add_wettkampfgruppe)

    app.root.LfReihenfolge = CTkScrollableFrame(app.root.FTab1, border_width=0, corner_radius=0, fg_color='transparent')
    app.root.LfReihenfolge.pack(expand=1 ,side='top', fill='both', padx=10, pady=10) 

    if len(app.Wettkampfgruppen) == 0:
        app.root.LNoGroups = CTkLabel(app.root.LfReihenfolge, text='Keine Gruppen angemeldet!', anchor='w')
        app.root.LNoGroups.grid(row=0, column=0, sticky=(W+E+N+S), padx=10, pady=5)
    else:
        app.zeichneAngemeldeteGruppen()

    app.root.BtnUebernehmen = CTkButton(app.root.FTab1, text='Gruppen übernehmen', command=lambda:uebernahme_gruppen(False), corner_radius=0)
    app.root.BtnUebernehmen.pack(side='bottom', fill='x', padx=10, pady=10)

def create_tab2(app):
    app.root.dg = CTkScrollableFrame(app.root.FTab2, border_width=0, fg_color='transparent')

    app.root.zeitnehmung = CTkFrame(app.root.FTab2, border_width=0, fg_color='transparent')
    app.root.BtnAnsichtWechseln = CTkButton(app.root.zeitnehmung, text='Ansicht wechseln', width=120, corner_radius=0, command=anzeige_umschalten)
    app.root.BtnAnsichtWechseln.pack(side='left', padx=5, pady=20, ipady=15) 
    app.root.CBDG = CTkComboBox(app.root.zeitnehmung, justify=CENTER, width=100, height=58, corner_radius=0, state='readonly', command=lade_zeitnehmungsdaten)
    app.root.CBDG.pack(side='left', padx=5, pady=20)
    app.root.BtnVorherigerDG = CTkButton(app.root.zeitnehmung, text='DG -', width=50, corner_radius=0, command=vorheriger_dg)
    app.root.BtnVorherigerDG.pack(side='left', padx=5, pady=20, ipady=15)
    app.root.BtnNaechsterDG = CTkButton(app.root.zeitnehmung, text='DG +', width=50, corner_radius=0, command=naechster_dg)
    app.root.BtnNaechsterDG.pack(side='left', padx=5, pady=20, ipady=15)
    app.root.BtnStart = CTkButton(app.root.zeitnehmung, text='Start', width=70, corner_radius=0, command=start, state=DISABLED)
    app.root.BtnStart.pack(side='left', padx=5, pady=20, ipady=15)
    app.root.BtnAllesStop = CTkButton(app.root.zeitnehmung, text='Alles Stop', width=90,  corner_radius=0, command=alles_stop, state=DISABLED)
    app.root.BtnAllesStop.pack(side='left', padx=5, pady=20, ipady=15)
    app.root.BtnWechsel = CTkButton(app.root.zeitnehmung, text='Bahn Wechsel', width=100, corner_radius=0, command=bahn_wechsel, state=DISABLED)
    app.root.BtnWechsel.pack(side='left', padx=5, pady=20, ipady=15)
    app.root.BtnZeitUebertragen = CTkButton(app.root.zeitnehmung, text='Zeit übertragen', width=110, corner_radius=0, command=werte_uebertragen, state=DISABLED)
    app.root.BtnZeitUebertragen.pack(side='left', padx=5, pady=20, ipady=15)

    app.root.LfBahnen = CTkFrame(app.root.FTab2, border_width=1, corner_radius=0, fg_color='transparent')

    app.root.CB1 = CTkCheckBox(app.root.LfBahnen, text='Bahn 1', variable=app.checked_Bahn_1, corner_radius=0, command=switch_bahn1_state)
    app.root.CB1.grid(row=0, column=0, padx=5, pady=(3,0))
    app.root.G1 = CTkLabel(app.root.LfBahnen, text='...', corner_radius=0, font=(app.GlobalFontArt, app.GlobalFontSizeTitle), state=DISABLED)
    app.root.G1 .grid(row=0, column=1, padx=5, pady=(5,0))
    app.root.T1 = CTkLabel(app.root.LfBahnen, text='00:00:00', corner_radius=0, font=(app.GlobalFontArt, app.GlobalFontSizeTitle), state=DISABLED)
    app.root.T1.grid(row=0, column=2, padx=5, pady=(5,0))
    app.root.LblFehler1 = CTkLabel(app.root.LfBahnen, text='Fehler')
    app.root.LblFehler1 .grid(row=0, column=3, padx=5, pady=(5,0))
    app.root.F1 = CTkEntry(app.root.LfBahnen, width=5, corner_radius=0)
    app.root.F1.grid(row=0, column=4, padx=5, pady=(5,0))
    app.root.B1 = CTkButton(app.root.LfBahnen, text='Stop', width=70, corner_radius=0, command=stop_1, state=DISABLED)
    app.root.B1.grid(row=0, column=5, padx=(0,5), pady=(5,0))

    app.root.CB2 = CTkCheckBox(app.root.LfBahnen, text='Bahn 2', variable=app.checked_Bahn_2, corner_radius=0, command=switch_bahn2_state)
    app.root.CB2.grid(row=1, column=0, padx=5, pady=(0,3))
    app.root.G2 = CTkLabel(app.root.LfBahnen, text='...', corner_radius=0, font=(app.GlobalFontArt, app.GlobalFontSizeTitle), state=DISABLED)
    app.root.G2 .grid(row=1, column=1, padx=5, pady=(0,5))
    app.root.T2 = CTkLabel(app.root.LfBahnen, text='00:00:00', corner_radius=0, font=(app.GlobalFontArt, app.GlobalFontSizeTitle), state=DISABLED)
    app.root.T2.grid(row=1, column=2, padx=5, pady=(0,5))
    app.root.LblFehler2 = CTkLabel(app.root.LfBahnen, text='Fehler')
    app.root.LblFehler2 .grid(row=1, column=3, padx=5, pady=(0,5))
    app.root.F2 = CTkEntry(app.root.LfBahnen, width=5, corner_radius=0)
    app.root.F2.grid(row=1, column=4, padx=5, pady=(0,5))
    app.root.B2 = CTkButton(app.root.LfBahnen, text='Stop', width=70, corner_radius=0, command=stop_2, state=DISABLED)
    app.root.B2.grid(row=1, column=5, padx=(0,5), pady=(0,5))

    app.root.korrektur = CTkFrame(app.root.FTab2, border_width=0, fg_color='transparent')

    app.root.BtnStopReset = CTkButton(app.root.korrektur, text='Stop and Reset', width=110, corner_radius=0, command=stop_reset, state=DISABLED)
    app.root.BtnStopReset.pack(side='left', padx=5, pady=20, ipady=15) 
    app.root.BtnLoeZ1 = CTkButton(app.root.korrektur, text='DG Zeit 1+2 löschen', width=120, corner_radius=0, command=zeit_1_loeschen)
    app.root.BtnLoeZ1.pack(side='left', padx=5, pady=20, ipady=15) 
    app.root.BtnLoeZ2 = CTkButton(app.root.korrektur, text='DG Zeit 2 löschen', width=120, corner_radius=0, command=zeit_2_loeschen)
    app.root.BtnLoeZ2.pack(side='left', padx=5, pady=20, ipady=15) 

def create_tab3(app):
    app.root.setupEingabe = CTkFrame(app.root.FTab3, border_width=1, corner_radius=0, fg_color='transparent')
    app.root.setupEingabe.pack(side='top', fill='x', padx=10, pady=5)
    app.root.CheckTastatur = CTkCheckBox(app.root.setupEingabe, text='Tastatur', corner_radius=0, variable=app.checked_Tastatur)
    app.root.CheckTastatur.grid(row=0, column=0, padx=10, pady=10)
    app.root.CheckGPIO = CTkCheckBox(app.root.setupEingabe, text='GPIO', variable=app.checked_GPIO, corner_radius=0, command=app.initGPIO)
    app.root.CheckGPIO.grid(row=0, column=1, pady=10)
    app.root.CheckRahmen = CTkCheckBox(app.root.setupEingabe, text='Rahmen ausblenden', variable=app.checked_Rahmen, corner_radius=0, command=update_rahmen_anzeige)
    app.root.CheckRahmen.grid(row=0, column=2, padx=10, pady=10)
    app.root.CheckKonsole = CTkCheckBox(app.root.setupEingabe, text='Konsole', variable=app.checked_Konsole, corner_radius=0)
    app.root.CheckKonsole.grid(row=0, column=3, pady=10)

    app.root.setupTasten = CTkFrame(app.root.FTab3, border_width=1, corner_radius=0, fg_color='transparent')
    app.root.setupTasten.pack(side='top', fill='x', padx=10, pady=5)
    app.root.Start_Taste_1_Label = CTkLabel(app.root.setupTasten, text='Start 1')
    app.root.Start_Taste_1_Label.grid(row=0, column=0, padx=10, pady=10)
    app.root.Start_Taste_1 = CTkEntry(app.root.setupTasten, width=30, corner_radius=0)
    app.root.Start_Taste_1.grid(row=0, column=1, pady=10)
    app.root.Stop_Taste_1_Label = CTkLabel(app.root.setupTasten, text='Stop 1')
    app.root.Stop_Taste_1_Label.grid(row=0, column=2, padx=10, pady=10)
    app.root.Stop_Taste_1 = CTkEntry(app.root.setupTasten, width=30, corner_radius=0)
    app.root.Stop_Taste_1.grid(row=0, column=3, pady=10)
    app.root.Start_Taste_2_Label = CTkLabel(app.root.setupTasten, text='Start 2')
    app.root.Start_Taste_2_Label.grid(row=0, column=4, padx=10, pady=10)
    app.root.Start_Taste_2 = CTkEntry(app.root.setupTasten, width=30, corner_radius=0)
    app.root.Start_Taste_2.grid(row=0, column=5, pady=10)
    app.root.Stop_Taste_2_Label = CTkLabel(app.root.setupTasten, text='Stop 2')
    app.root.Stop_Taste_2_Label.grid(row=0, column=6, padx=10,pady=10)
    app.root.Stop_Taste_2 = CTkEntry(app.root.setupTasten, width=30, corner_radius=0)
    app.root.Stop_Taste_2.grid(row=0, column=7, pady=10)

    app.root.Start_Taste_1.insert(0, app.Taste_Start_1)
    app.root.Stop_Taste_1.insert(0, app.Taste_Stop_1)
    app.root.Start_Taste_2.insert(0, app.Taste_Start_2)
    app.root.Stop_Taste_2.insert(0, app.Taste_Stop_2)

    app.root.setupGPIO = CTkFrame(app.root.FTab3, border_width=1, corner_radius=0, fg_color='transparent')
    app.root.setupGPIO.pack(side='top', fill='x', padx=10, pady=5)
    app.root.Start_GPIO_1_Label = CTkLabel(app.root.setupGPIO, text='Start 1')
    app.root.Start_GPIO_1_Label.grid(row=0, column=0, padx=10, pady=10)
    app.root.Start_GPIO_1 = CTkEntry(app.root.setupGPIO, width=30, corner_radius=0)
    app.root.Start_GPIO_1.grid(row=0, column=1, pady=10)
    app.root.Stop_GPIO_1_Label = CTkLabel(app.root.setupGPIO, text='Stop 1')
    app.root.Stop_GPIO_1_Label.grid(row=0, column=2, padx=10, pady=10)
    app.root.Stop_GPIO_1 = CTkEntry(app.root.setupGPIO, width=30, corner_radius=0)
    app.root.Stop_GPIO_1.grid(row=0, column=3, pady=10)
    app.root.Start_GPIO_2_Label = CTkLabel(app.root.setupGPIO, text='Start 2')
    app.root.Start_GPIO_2_Label.grid(row=0, column=4, padx=10, pady=10)
    app.root.Start_GPIO_2 = CTkEntry(app.root.setupGPIO, width=30, corner_radius=0)
    app.root.Start_GPIO_2.grid(row=0, column=5, pady=10)
    app.root.Stop_GPIO_2_Label = CTkLabel(app.root.setupGPIO, text='Stop 2')
    app.root.Stop_GPIO_2_Label.grid(row=0, column=6, padx=10,pady=10)
    app.root.Stop_GPIO_2 = CTkEntry(app.root.setupGPIO, width=30, corner_radius=0)
    app.root.Stop_GPIO_2.grid(row=0, column=7, pady=10)

    app.root.Start_GPIO_1.insert(0, app.GPIO_Start_1)
    app.root.Stop_GPIO_1.insert(0, app.GPIO_Stop_1)
    app.root.Start_GPIO_2.insert(0, app.GPIO_Start_2)
    app.root.Stop_GPIO_2.insert(0, app.GPIO_Stop_2)

    app.root.setupStyle = CTkFrame(app.root.FTab3, border_width=1, corner_radius=0, fg_color='transparent')
    app.root.setupStyle.pack(side='top', fill='x', padx=10, pady=5)
    app.root.SGZL = CTkLabel(app.root.setupStyle, text='Schriftgröße Zeit')
    app.root.SGZL.grid(row=0, column=0, padx=10, pady=10, sticky=(W))
    app.root.SGZ = IntSpinbox(app.root.setupStyle, command=update_font_size_zeit)
    app.root.SGZ.grid(row=0, column=1, padx=10, pady=10)
    app.root.SGZ.set(app.AnzeigeFontSizeTime)
    app.root.SGGL = CTkLabel(app.root.setupStyle, text='Schriftgröße Gruppe')
    app.root.SGGL.grid(row=0, column=2, padx=10, pady=10, sticky=(W))
    app.root.SGG = IntSpinbox(app.root.setupStyle, command=update_font_size_gruppe)
    app.root.SGG.grid(row=0, column=3, padx=10, pady=10)
    app.root.SGG.set(app.AnzeigeFontSizeGroup)

    app.root.setupAutoAnpassung = CTkFrame(app.root.FTab3, border_width=1, corner_radius=0, fg_color='transparent')
    app.root.setupAutoAnpassung.pack(side='top', fill='x', padx=10, pady=5)
    app.root.LblAnpassungTitel = CTkLabel(app.root.setupAutoAnpassung, text='Aktuelle Fensterhöhe')
    app.root.LblAnpassungTitel.grid(row=0, column=0, padx=10, pady=10, sticky=(W))
    app.root.LblAnpassungWert = CTkLabel(app.root.setupAutoAnpassung, text=app.screen_height)
    app.root.LblAnpassungWert.grid(row=0, column=1, padx=10, pady=10, sticky=(W))
    app.root.LblFaktorZeit = CTkLabel(app.root.setupAutoAnpassung, text='Faktor Zeit')
    app.root.LblFaktorZeit.grid(row=1, column=0, padx=10, pady=2, sticky=(W))
    app.root.SBFaktorZeit = IntSpinbox(app.root.setupAutoAnpassung)
    app.root.SBFaktorZeit.grid(row=1, column=1, padx=10, pady=2)
    app.root.SBFaktorZeit.set(3)
    app.root.LblFaktorGruppen = CTkLabel(app.root.setupAutoAnpassung, text='Faktor Gruppen')
    app.root.LblFaktorGruppen.grid(row=2, column=0, padx=10, pady=2, sticky=(W))
    app.root.SBFaktorGruppen = IntSpinbox(app.root.setupAutoAnpassung)
    app.root.SBFaktorGruppen.grid(row=2, column=1, padx=10, pady=2)
    app.root.SBFaktorGruppen.set(20)
    app.root.LblFaktorInfo = CTkLabel(app.root.setupAutoAnpassung, text='Faktor Info')
    app.root.LblFaktorInfo.grid(row=3, column=0, padx=10, pady=2, sticky=(W))
    app.root.SBFaktorInfo = IntSpinbox(app.root.setupAutoAnpassung)
    app.root.SBFaktorInfo.grid(row=3, column=1, padx=10, pady=2)
    app.root.SBFaktorInfo.set(65)
    app.root.LblFaktorAuswertung = CTkLabel(app.root.setupAutoAnpassung, text='Faktor Auswertung')
    app.root.LblFaktorAuswertung.grid(row=4, column=0, padx=10, pady=2, sticky=(W))
    app.root.SBFaktorAuswertung = IntSpinbox(app.root.setupAutoAnpassung)
    app.root.SBFaktorAuswertung.grid(row=4, column=1, padx=10, pady=2)
    app.root.SBFaktorAuswertung.set(40)
    app.root.BtnChangeStyle = CTkButton(app.root.setupAutoAnpassung, text='Anzeige Autoanpassung', corner_radius=0, command=change_font_size_from_windowsize)
    app.root.BtnChangeStyle.grid(row=5, column=0, padx=10, pady=10, ipadx=10)

    if app.Testmodus == True:
        app.root.setupTest = CTkFrame(app.root.FTab3, border_width=1, corner_radius=0, fg_color='transparent')
        app.root.setupTest.pack(side='bottom', fill='x', padx=10, pady=5)
        app.root.LblAnzahlGruppen = CTkLabel(app.root.setupTest, text='Anzahl Testgruppen')
        app.root.LblAnzahlGruppen.grid(row=0, column=0, padx=10, pady=10)
        app.root.SBAnzahlGruppen = IntSpinbox(app.root.setupTest)
        app.root.SBAnzahlGruppen.grid(row=0, column=1, padx=10, pady=10)
        app.root.LblAnzahlDamenGruppen = CTkLabel(app.root.setupTest, text='Anzahl Testdamengruppen')
        app.root.LblAnzahlDamenGruppen.grid(row=0, column=2, padx=10, pady=10)
        app.root.SBAnzahlDamenGruppen = IntSpinbox(app.root.setupTest)
        app.root.SBAnzahlDamenGruppen.grid(row=0, column=3, padx=10, pady=10)
        app.root.BtnAnzahlGruppen = CTkButton(app.root.setupTest, text='Erstellen', corner_radius=0, command=test_gruppen_erstellen)
        app.root.BtnAnzahlGruppen.grid(row=0, column=4, padx=10, pady=10)
       

def show_anzeige(app):
    app.anzeige = CTkToplevel()
    app.anzeige.title(app.TitleAnzeige)
    app.anzeige.minsize(700, 400)
    app.anzeige.configure(fg_color=app.AnzeigeBackgroundColor)
    # app.anzeige.iconbitmap(app.FileIcon)

    app.anzeige.frame = CTkFrame(app.anzeige, border_width=0, corner_radius=0, fg_color=app.AnzeigeBackgroundColor)
    app.anzeige.frame.pack(expand=1, side=TOP, fill=BOTH, padx=20, pady=20)

    app.anzeige.G1 = CTkLabel(app.anzeige.frame, text='', anchor='nw', corner_radius=0, text_color=app.AnzeigeGroupColor, fg_color=app.AnzeigeBackgroundColor, font=(app.GlobalFontArt, app.AnzeigeFontSizeGroup))
    app.anzeige.Z1 = CTkLabel(app.anzeige.frame, text='00:00:00', anchor='center', corner_radius=0, text_color=app.AnzeigeTimeColor, fg_color=app.AnzeigeBackgroundColor, font=(app.GlobalFontArt, app.AnzeigeFontSizeTime))
    app.anzeige.Z2 = CTkLabel(app.anzeige.frame, text='00:00:00', anchor='center', corner_radius=0, text_color=app.AnzeigeTimeColor, fg_color=app.AnzeigeBackgroundColor, font=(app.GlobalFontArt, app.AnzeigeFontSizeTime))
    app.anzeige.G2 = CTkLabel(app.anzeige.frame, text='', anchor='ne', corner_radius=0, text_color=app.AnzeigeGroup2Color, fg_color=app.AnzeigeBackgroundColor, font=(app.GlobalFontArt, app.AnzeigeFontSizeGroup))
    
    app.anzeige.ERG = CTkFrame(app.anzeige.frame, border_width=0, corner_radius=0)
    app.anzeige.ERG.pack(expand=1, side=TOP, fill=BOTH)

    app.anzeige.INFO = CTkFrame(app.anzeige.frame, fg_color=app.AnzeigeNextColor, border_width=0, corner_radius=0)
    app.anzeige.INFO.pack(expand=0, side='bottom' , fill='x', pady=20, padx=20)

    app.changeFontSizeFromWindowSize()
